# -*- coding: utf-8 -*-
"""
通用配置文件

所有可调整的游戏参数集中管理
"""
from common.common_enum import ItemType, ItemRarity



items = {
    "fish":{
        "name": "🐟 新鲜鱼干",
        "description": "桌宠最爱的零食",
        "item_type": ItemType.FOOD,
        "rarity": ItemRarity.COMMON,
        "icon": "🐟",
        "boost_value": 20,
        "protection_duration": 300,
        "price": 10,
        "sell_price": 5,
    },
           "cake": {
                "name": "🎂 小蛋糕",
                "description": "甜美的蛋糕，让桌宠开心一整天",
                "item_type": ItemType.FOOD,
                "rarity": ItemRarity.RARE,
                "icon": "🎂",
                "boost_value": 35,
                "protection_duration": 600,
                "price": 25,
                "sell_price": 12},
            "pizza": {
                "name": "🍕 迷你披萨",
                "description": "美味的披萨切片，丰盛的一餐",
                "item_type": ItemType.FOOD,
                "rarity": ItemRarity.RARE,
                "icon": "🍕",
                "boost_value": 50,
                "protection_duration": 900,
                "price": 30,
                "sell_price": 15,
            },
            "star_candy": {
                "name": "⭐ 星星糖果",
                "description": "神奇的糖果，大幅提升饱食度",
                "item_type": ItemType.FOOD,
                "rarity": ItemRarity.EPIC,
                "icon": "⭐",
                "boost_value": 80,
                "protection_duration": 1800,
                "price": 80,
                "sell_price": 40,
            },
            "milk": {
                "name": "🥛 温热牛奶",
                "description": "温暖的牛奶，解渴又健康",
                "item_type": ItemType.DRINK,
                "rarity": ItemRarity.COMMON,
                "icon": "ju",
                "boost_value": 20,
                "protection_duration": 300,
                "price": 8,
                "sell_price": 4,
            },
            "juice": {
                "name": "🧃 鲜榨果汁",
                "description": "新鲜水果榨汁，清爽解渴",
                "item_type": ItemType.DRINK,
                "rarity": ItemRarity.COMMON,
                "icon": "🧃",
                "boost_value": 25,
                "protection_duration": 360,
                "price": 12,
                "sell_price": 6,
            },
            "bubble_tea": {
                "name": "🧋 珍珠奶茶",
                "description": "甜甜的奶茶，幸福感满满",
                "item_type": ItemType.DRINK,
                "rarity": ItemRarity.RARE,
                "icon": "🧋",
                "boost_value": 40,
                "protection_duration": 720,
                "price": 22,
                "sell_price": 11,
            },
            "magic_potion": {
                "name": "🧪 魔法药水",
                "description": "神秘的药水，大幅提升饱食度",
                "item_type": ItemType.DRINK,
                "rarity": ItemRarity.EPIC,
                "icon": "🧪",
                "boost_value": 70,
                "protection_duration": 1500,
                "price": 70,
                "sell_price": 35,
            },
            "yarn_ball": {
                "name": "� 毛线球",
                "description": "猫咪最爱的玩具，玩得不亦乐乎",
                "item_type": ItemType.TOY,
                "rarity": ItemRarity.COMMON,
                "icon": "�",
                "boost_value": 20,
                "protection_duration": 300,
                "price": 10,
                "sell_price": 5,
            },
            "feather_wand": {
                "name": "🪶 羽毛棒",
                "description": "逗猫神器，让桌宠兴奋不已",
                "item_type": ItemType.TOY,
                "rarity": ItemRarity.RARE,
                "icon": "🪶",
                "boost_value": 35,
                "protection_duration": 600,
                "price": 25,
                "sell_price": 12,
            },
            "puzzle_toy": {
                "name": "� 益智玩具",
                "description": "锻炼脑力的好玩具",
                "item_type": ItemType.TOY,
                "rarity": ItemRarity.RARE,
                "icon": "�",
                "boost_value": 30,
                "protection_duration": 480,
                "price": 20,
                "sell_price": 10,
            },
            "golden_bell": {
                "name": "🔔 金色铃铛",
                "id": "golden_bell",
                "name": "🔔 金色铃铛",
                "description": "闪闪发光的铃铛，让桌宠无比快乐",
                "item_type": ItemType.TOY,
                "rarity": ItemRarity.EPIC,
                "icon": "🔔",
                "boost_value": 60,
                "protection_duration": 1200,
                "price": 60,
                "sell_price": 30,
            },
}